# Generated by Django 5.0.6 on 2024-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='market_purpose',
            field=models.CharField(blank=True, choices=[('FR', 'FOR RENT'), ('FH', 'FOR HIRE'), ('FS', 'FOR SALE')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('MU', 'Meru'), ('MA', 'Mombasa'), ('KU', 'Kisumu'), ('KI', 'Kisii'), ('MS', 'Machakos'), ('NI', 'Nairobi'), ('GA', 'Garissa'), ('NA', 'Nyamira'), ('KO', 'Kericho'), ('EM', 'Embu'), ('NV', 'Naivasha'), ('NK', 'Nakuru'), ('NM', 'Namanga'), ('MI', 'Migori'), ('KG', 'Kakamega'), ('EL', 'Eldoret'), ('BM', 'Bungoma'), ('KL', 'Kwale'), ('LM', 'Limuru'), ('KR', 'Kilgoris'), ('KT', 'Kitengela'), ('KN', 'Karen'), ('LV', 'Lavington'), ('NR', 'Nyeri'), ('MA', 'Mwea'), ('HB', 'Homa Bay'), ('OG', 'Ogembo'), ('SY', 'Siaya'), ('KF', 'Kilifi'), ('MD', 'Malindi'), ('NG', 'Namanga')], max_length=2),
        ),
    ]
