# Generated by Django 5.0.6 on 2024-07-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_market_purpose_alter_car_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='market_purpose',
            new_name='tag',
        ),
    ]
