# Generated by Django 5.0.6 on 2024-07-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_market_purpose_car_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tag',
            field=models.CharField(blank=True, choices=[('FOR RENT', 'FOR RENT'), ('FOR HIRE', 'FOR HIRE'), ('FOR SALE', 'FOR SALE')], max_length=9, null=True),
        ),
    ]
