# Generated by Django 5.0.6 on 2024-07-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('Used', 'Used'), ('New', 'New'), ('Refurbished', 'Refurbished')], max_length=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('Meru', 'Meru'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Machakos', 'Machakos'), ('Nairobi', 'Nairobi'), ('Garissa', 'Garissa'), ('Nyamira', 'Nyamira'), ('Kericho', 'Kericho'), ('Embu', 'Embu'), ('Naivasha', 'Naivasha'), ('Nakuru', 'Nakuru'), ('Namanga', 'Namanga'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Eldoret', 'Eldoret'), ('Bungoma', 'Bungoma'), ('Kwale', 'Kwale'), ('Limuru', 'Limuru'), ('Kolgoris', 'Kilgoris'), ('Kitengela', 'Kitengela'), ('Karen', 'Karen'), ('Lavington', 'Lavington'), ('Nyeri', 'Nyeri'), ('Mwea', 'Mwea'), ('Homa Bay', 'Homa Bay'), ('Ogembo', 'Ogembo'), ('Siaya', 'Siaya'), ('Kilifi', 'Kilifi'), ('Malindi', 'Malindi'), ('Namanga', 'Namanga')], max_length=9),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Automated Manual', 'Automated Manual'), ('Continuos Variable', 'Continuosly Variable')], max_length=18),
        ),
    ]
